# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(249, 479)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color:#000;")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(180, 160, 70, 311))
        self.frame.setStyleSheet("QPushButton {\n"
"  background-color: rgb(255, 147, 0);\n"
"  color: white;\n"
"  padding: 15px 32px;\n"
"  text-align: center;\n"
"  font-size: 20px;\n"
"  border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color:rgb(255, 199, 69); \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.div_btn = QtWidgets.QPushButton(self.frame)
        self.div_btn.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.div_btn.setObjectName("div_btn")
        self.sub_btn = QtWidgets.QPushButton(self.frame)
        self.sub_btn.setGeometry(QtCore.QRect(10, 130, 51, 51))
        self.sub_btn.setObjectName("sub_btn")
        self.equal_btn = QtWidgets.QPushButton(self.frame)
        self.equal_btn.setGeometry(QtCore.QRect(10, 250, 51, 51))
        self.equal_btn.setObjectName("equal_btn")
        self.plus_btn = QtWidgets.QPushButton(self.frame)
        self.plus_btn.setGeometry(QtCore.QRect(10, 190, 51, 51))
        self.plus_btn.setObjectName("plus_btn")
        self.mul_btn = QtWidgets.QPushButton(self.frame)
        self.mul_btn.setGeometry(QtCore.QRect(10, 70, 51, 51))
        self.mul_btn.setObjectName("mul_btn")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 220, 181, 251))
        self.frame_2.setStyleSheet("QPushButton {\n"
"  background-color:rgb(51, 51, 51); /* Green */\n"
"  border: none;\n"
"  color: white;\n"
"  padding: 15px 32px;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  font-size: 20px;\n"
"  border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color:rgb(113, 115, 115); /* Green */\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.dot = QtWidgets.QPushButton(self.frame_2)
        self.dot.setGeometry(QtCore.QRect(130, 190, 51, 51))
        self.dot.setObjectName("dot")
        self.number3 = QtWidgets.QPushButton(self.frame_2)
        self.number3.setGeometry(QtCore.QRect(130, 130, 51, 51))
        self.number3.setObjectName("number3")
        self.number6 = QtWidgets.QPushButton(self.frame_2)
        self.number6.setGeometry(QtCore.QRect(130, 70, 51, 51))
        self.number6.setObjectName("number6")
        self.number9 = QtWidgets.QPushButton(self.frame_2)
        self.number9.setGeometry(QtCore.QRect(130, 10, 51, 51))
        self.number9.setObjectName("number9")
        self.number2 = QtWidgets.QPushButton(self.frame_2)
        self.number2.setGeometry(QtCore.QRect(70, 130, 51, 51))
        self.number2.setObjectName("number2")
        self.number5 = QtWidgets.QPushButton(self.frame_2)
        self.number5.setGeometry(QtCore.QRect(70, 70, 51, 51))
        self.number5.setObjectName("number5")
        self.number1 = QtWidgets.QPushButton(self.frame_2)
        self.number1.setGeometry(QtCore.QRect(10, 130, 51, 51))
        self.number1.setObjectName("number1")
        self.number4 = QtWidgets.QPushButton(self.frame_2)
        self.number4.setGeometry(QtCore.QRect(10, 70, 51, 51))
        self.number4.setObjectName("number4")
        self.number8 = QtWidgets.QPushButton(self.frame_2)
        self.number8.setGeometry(QtCore.QRect(70, 10, 51, 51))
        self.number8.setObjectName("number8")
        self.number7 = QtWidgets.QPushButton(self.frame_2)
        self.number7.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.number7.setObjectName("number7")
        self.number0 = QtWidgets.QPushButton(self.frame_2)
        self.number0.setGeometry(QtCore.QRect(10, 190, 111, 51))
        self.number0.setStyleSheet("text-align:left;\n"
"padding-left:18;")
        self.number0.setObjectName("number0")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(0, 160, 181, 61))
        self.frame_3.setStyleSheet("QPushButton {\n"
"  background-color:rgb(164, 164, 164); /* Green */\n"
"  border: none;\n"
"  color: white;\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  font-size: 20px;\n"
"  border-radius:25px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color:rgb(124, 124, 124); /* Green */\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.percentage = QtWidgets.QPushButton(self.frame_3)
        self.percentage.setGeometry(QtCore.QRect(130, 10, 51, 51))
        self.percentage.setObjectName("percentage")
        self.all_clear = QtWidgets.QPushButton(self.frame_3)
        self.all_clear.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.all_clear.setObjectName("all_clear")
        self.neg_pos = QtWidgets.QPushButton(self.frame_3)
        self.neg_pos.setGeometry(QtCore.QRect(70, 10, 51, 51))
        self.neg_pos.setObjectName("neg_pos")
        self.clear = QtWidgets.QPushButton(self.frame_3)
        self.clear.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.clear.setObjectName("clear")
        self.result = QtWidgets.QLineEdit(Form)
        self.result.setGeometry(QtCore.QRect(0, 90, 251, 61))
        self.result.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.result.setStyleSheet("color:#fff;\n"
"border:none;\n"
"font: 40pt \"MS Shell Dlg 2\";")
        self.result.setText("")
        self.result.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.result.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.div_btn.setText(_translate("Form", "÷"))
        self.sub_btn.setText(_translate("Form", "–"))
        self.equal_btn.setText(_translate("Form", "="))
        self.plus_btn.setText(_translate("Form", "+"))
        self.mul_btn.setText(_translate("Form", "×"))
        self.dot.setText(_translate("Form", "."))
        self.number3.setText(_translate("Form", "3"))
        self.number6.setText(_translate("Form", "6"))
        self.number9.setText(_translate("Form", "9"))
        self.number2.setText(_translate("Form", "2"))
        self.number5.setText(_translate("Form", "5"))
        self.number1.setText(_translate("Form", "1"))
        self.number4.setText(_translate("Form", "4"))
        self.number8.setText(_translate("Form", "8"))
        self.number7.setText(_translate("Form", "7"))
        self.number0.setText(_translate("Form", "0"))
        self.percentage.setText(_translate("Form", "%"))
        self.all_clear.setText(_translate("Form", "AC"))
        self.neg_pos.setText(_translate("Form", "+⁄–"))
        self.clear.setText(_translate("Form", "C"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
